config:
  host: devx-helloworld-springboot-olhzo.nonp-dev-4.use1.eng-nonprod.flexport.internal
  namespace: devx-helloworld-springboot-olhzo-dev
  image:
    name: artifactory.flexport.io/devx-helloworld-springboot-olhzo-docker-dev-local/devx-helloworld-springboot-olhzo
    tag: 0.0.1-SNAPSHOT
